### ISSUE TITLE
TypeError while splitting

### ISSUE THREAD

**Issue by salicylic** [matakuka/gridsplitter#1]
I'm running QGIS 2.12.1-Lyon on MacOS 10.11.2. While trying to split a layer with gridSplitter 0.3.4, I get the following python error:
```
TypeError: %d format: a number is required, not str 
Traceback (most recent call last):
  File "/Volumes/Data/Users/jan/.qgis2/python/plugins/gridSplitter/gridSplitter.py", line 185, in run
    self.operate()
  File "/Volumes/Data/Users/jan/.qgis2/python/plugins/gridSplitter/gridSplitter.py", line 419, in operate
    k= processing.runalg('qgis:intersection', layertocut, self.temp , folder+ pref +'%04d' %(str(i))+"_"+'%04d' %(str(j))+".shp")
TypeError: %d format: a number is required, not str
```

**Comment by matakuka** [comment]
I think I fixed the typo, but I don't have a good testing environment at the moment (no macOS). 
Just update gridSplitter.py with the new github version and please let me know if it works. 
Thanks

**Comment by salicylic** [comment]
Works now. Thanks!
